services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./core/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5433:5432"

  backend:
    build:
      context: .
      dockerfile: core/worker/Dockerfile
    working_dir: /app/core/worker
    command: sh -c "npx graphile-worker --schema-only --connection $$DATABASE_URL && node index.js"
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "4000:4000" 

  frontend:
    build:
      context: ./web
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db-data: